version: '3.4'

services:
  penny-planner-db:
    image: postgres:latest
    container_name: penny-planner.db

  penny-planner-cache:
    image: redis
    container_name: penny-planner.cache

  penny-planner.api:
    image: ${DOCKER_REGISTRY-}pennyplanner
    container_name: penny-planner.api
    build:
      context: .
      dockerfile: src/PennyPlanner.API/Dockerfile
    depends_on:
      - penny-planner-db
      - penny-planner-cache

  penny-planner-seq:
    image: datalust/seq:latest
    container_name: penny-planner.seq

volumes:
  postgres_data: