version: '3.4'

services:
  penny-planner-db:
    restart: always
    environment:
      - POSTGRES_DB=budget
      - POSTGRES_USER=penny
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  penny-planner-cache:
    restart: always
    ports:
      - "6379:6379"

  penny-planner.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 8000:80
      - 5001:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  penny-planner-seq:
    restart: always
    environment:
    - ACCEPT_EULA=Y
    ports:
    - "5341:5341"
    - "8101:80"
    networks:
    - default  