name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    #environment: 
      #name: Development
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PennyPlanner.sln
      
    #- name: Set Environment Variables
      #run: |
        #echo "Setting environment variables..."
      
    - name: Build
      run: dotnet build PennyPlanner.sln --no-restore
    - name: Test
      run: dotnet test PennyPlanner.sln --no-build --verbosity normal
